name: Docker Deployment
on: workflow_dispatch
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Login to the dev server
          run: |
            ssh -i $GITHUB_WORKSPACE/serverlogin/dockermachine.pem -o StrictHostKeyChecking=no ubuntu@ec2-34-230-90-47.compute-1.amazonaws.com 'echo "Logged in successfully"'
            cd /home/ubuntu
            ls -lthr
            docker --version